(function(e,a){a.SliderFormController=a.FormController.extend({},{optionControllers:{},dependencies:{},preview_wrapper:null,init:function(b,d){var c=this;this._super(b,d);this.changeShortcode();this.optionControllers.alias.on("change",function(){c.changeShortcode()});e("#mpsl-slider-settings-tabs").tabs({activate:function(c,b){a.CodeMirrorControl.refreshEditors(b.newPanel)}});this.preview_wrapper=e(".mpsl-slider-preview");this.previewIframe=this.preview_wrapper.find("iframe");this.preloader=this.preview_wrapper.find(".mpsl-preloader");
this.previewUrl=a.Vars.menu_url;this.previewSliderId=null;this.resolutionWrapper=this.preview_wrapper.find(".mpsl-resolution-buttons-wrapper");this.desktopIcon=this.preview_wrapper.find(".desktop");this.previewUrl=a.Functions.addParamToUrl(this.previewUrl,"view","preview");this.previewUrl=a.Functions.addParamToUrl(this.previewUrl,"type","slider");this.preview_wrapper.dialog({resizable:!1,draggable:!1,autoOpen:!1,modal:!0,width:e(window).width()-100,height:e(window).height()-100,title:a.Vars.lang.preview_dialog_title,
closeText:"",dialogClass:"mpsl-preview-dialog",close:function(){(c.previewIframe[0].contentDocument||c.previewIframe[0].contentWindow.document).documentElement.innerHTML=""},open:function(){c.preloader.show();c.previewUrl=a.Functions.removeParamFromUrl(c.previewUrl,"slider_id");c.previewUrl=a.Functions.addParamToUrl(c.previewUrl,"slider_id",c.previewSliderId);c.previewIframe.attr("src",c.previewUrl);c.previewIframe.width("100%");c.desktopIcon.siblings().removeClass("active");c.desktopIcon.addClass("active")},
create:function(){c.resolutionWrapper.removeClass("hidden")}});this.resBtns=[{type:"desktop",resolution:"100%"},{type:"tablet",resolution:"768px"},{type:"mobile",resolution:"480px"}];this.resBtns.forEach(function(a){c.preview_wrapper.on("click","."+a.type,function(){c.previewIframe.width(a.resolution);e(this).siblings().removeClass("active");e(this).addClass("active")})});this.previewIframe.on("load",function(){c.preloader.hide()})},changeShortcode:function(b){this.optionControllers.shortcode.setValue("["+
a.Vars.settings.shortcode_name+" "+this.optionControllers.alias.getValue()+"]")},disableBtns:function(){this.element.find("#update_slider, #delete_slider, #create_slider, #edit_slides").attr("disabled","disabled")},enableBtns:function(){this.element.find("#update_slider, #delete_slider, #create_slider, #edit_slides").removeAttr("disabled","disabled")},"#update_slider, #slider_preview click":function(b){var d="slider_preview"===e(b).attr("id"),c=this;d||this.disableBtns();if(c.verifyOptions()){b=this.getFormData();
b={action:"mpsl_update_slider",nonce:a.Vars.nonces.update_slider,options:JSON.stringify(b),preview:d};var f=a.Vars.page.id;f&&(b.id=f);e.ajax({type:"POST",url:a.Vars.ajax_url,data:b,success:function(b){d?(c.previewSliderId=f,c.preview_wrapper.dialog("open")):(c.enableBtns(),b.hasOwnProperty("result")&&(!0===b.result?a.Functions.showMessage(a.Vars.lang.slider_updated,a.Functions.MSG_SUCCESS_TYPE):a.Functions.showMessage(a.Vars.lang.slider_update_error+b.error,a.Functions.MSG_ERROR_TYPE)))},error:function(b){b=
e.parseJSON(b.responseText);b.debug?console.log(b.message):a.Functions.showMessage(b.message,a.Functions.MSG_ERROR_TYPE);c.enableBtns()},dataType:"JSON"})}else c.enableBtns()},"#create_slider click":function(b){var d=this;d.disableBtns();d.verifyOptions()?(b=d.getFormData(),b={action:"mpsl_create_slider",nonce:a.Vars.nonces.create_slider,options:JSON.stringify(b)},e.ajax({type:"POST",url:a.Vars.ajax_url,data:b,success:function(c){if(c.hasOwnProperty("result"))if(!0===c.result){a.Functions.showMessage(a.Vars.lang.slider_created,
a.Functions.MSG_SUCCESS_TYPE);var b=a.Functions.removeParamFromUrl(window.location.href,"view"),b=a.Functions.addParamsToUrl(b,{view:"slides",id:c.id});window.location.href=b}else a.Functions.showMessage(c.error,a.Functions.MSG_ERROR_TYPE);else a.Functions.showMessage(a.Vars.lang.ajax_result_not_found,a.Functions.MSG_ERROR_TYPE);d.enableBtns()},error:function(c){var b=e.parseJSON(c.responseText);b.debug?console.log(b.message):a.Functions.showMessage(b.message,a.Functions.MSG_ERROR_TYPE);d.enableBtns();
console.error(c)},dataType:"JSON"})):d.enableBtns()},"#delete_slider click":function(b){var d=this;this.disableBtns();b=a.Vars.page.id;if(0==confirm(a.Vars.lang.slider_want_delete_single.replace("%d",b)))return!0;var c={action:"mpsl_delete_slider",nonce:a.Vars.nonces.delete_slider};b&&(c.id=b);e.ajax({type:"POST",url:a.Vars.ajax_url,data:c,success:function(b){d.enableBtns();b.hasOwnProperty("result")?1==b.result?(a.Functions.showMessage(a.Vars.lang.slider_deleted,a.Functions.MSG_SUCCESS_TYPE),b=a.Functions.removeParamsFromUrl(window.location.href,
["view","id"]),window.location.href=b):a.Functions.showMessage(b.error,a.Functions.MSG_ERROR_TYPE):a.Functions.showMessage(a.Vars.lang.ajax_result_not_found,a.Functions.MSG_ERROR_TYPE);d.enableBtns()},error:function(b){b=e.parseJSON(b.responseText);b.debug?console.log(b.message):a.Functions.showMessage(b.message,a.Functions.MSG_ERROR_TYPE);d.enableBtns()},dataType:"JSON"})}})})(jQuery,MPSL);jQuery(function(e){new MPSL.SliderFormController(e(".mpsl-slider-settings-wrapper"))});
